### ISSUE TITLE
deobfuscated code

### ISSUE THREAD

**Issue by maciejopalinski** [samay825/InSta-Reseter#2]
sorry made mistake because i dont know the language python sir i dont understand i am sorry

**Comment by codes-team** [comment]
> # This project seems to be malware.
> 
> I am attaching the following files:
> - `deobf.py.txt` - script that I wrote and used to deobfuscate this malware
> - `source-wo-comments.py.txt` - deobfuscated script with removed misleading comments
> 
> # How to deobfuscate code:
> ```
> python deobf.py.txt ./path/to/main.py > source.py
> ```
> 
> After deobfuscating the code, we can see that it contains large comments that make reading the code very difficult.
> 
> After analyzing the source code, it seems to **only send a password reset request** using instagram api, but the fact it is obfuscated using 400 layers **is very suspicious**.
> 
> # Never run code that is obfuscated.
> 
> [source-wo-comments.py.txt](https://github.com/samay825/InSta-Reseter/files/14548136/source-wo-comments.py.txt)
> [deobf.py.txt](https://github.com/samay825/InSta-Reseter/files/14548137/deobf.py.txt)
> 

bro i need to talk to you do you have telegram?

**Comment by samay825** [comment]
its okay brother
